/* Auto-generated from memtypes.c by gawk. */
/* Do not edit! */

#ifndef _QUAGGA_MEMTYPES_H
#define _QUAGGA_MEMTYPES_H

enum
{
    MTYPE_VECTOR = 0,
    MTYPE_VECTOR_INDEX,
    MTYPE_LINK_LIST,
    MTYPE_LINK_NODE,
    MTYPE_HASH,
    MTYPE_HASH_BACKET,
    MTYPE_HASH_INDEX,
    MTYPE_PQUEUE,
    MTYPE_PQUEUE_DATA,
    MTYPE_VERTEX,
    MTYPE_SPFTREE,
    MTYPE_TOPO,
    MTYPE_PASS_TREE,
    MTYPE_PASS_TREENODE,
    MTYPE_ROUTER,
    MTYPE_LINK_RECORD,
    MTYPE_PATH,
    MTYPE_CPATH,
    MTYPE_FIFO,
    MEM_QCCS_SRLG_EXCLUDE,
    MTYPE_INT,
    MTYPE_PASSOBJ,
    MTYPE_NODEID,
    MTYPE_EDGE,
    MTYPE_MAX,
};


#endif /* _QUAGGA_MEMTYPES_H */

